### PR TITLE
Fix lifecycle

### PR DESCRIPTION
**Pull request by alon-ne**
Rename field 'fileLifecycle' of Destination to 'lifecycle', add assertion and demo operation

### CODE REVIEW

**Comment by DorKatz17** [comment]
@alon-ne isn't that breaking changes?

**Review by gava — APPROVED** [review]

**Comment by alon-ne** [comment]
> @alon-ne isn't that breaking changes?

If by breaking you mean it breaks the non-working behavior we had before then yes :D You'll have to change your code from calling "setFileLifecycle" to setLifecycle"

**Comment by DorKatz17** [comment]
i mean compilation error on `setFileLifecycle()`
i will changes it to `setLifecycle()` but i guess there are some other users that are not aware of this issue and might break their builds

**Comment by alon-ne** [comment]
> there are some other users

I get what you're saying, will keep the old one for BC

**Review by Elad-Laufer — APPROVED** [review]

**Pull request merged**
