### PR TITLE
closing 40x response if response is closable

### PR DESCRIPTION
**Pull request by uriavraham**
@Elad-Laufer I made the PR here, but I'm not sure- if this is merged, will it be compatible with the version we're using (1.19.0)? I'm asking since I know there were compatibility issues of the snapshot lately (I don't know if on purpose or not).

### CODE REVIEW

**Comment by Elad-Laufer** [comment]
Did you base the change on the master branch or the 1.x?

**Comment by uriavraham** [comment]
On the master branch

**Comment by Elad-Laufer** [comment]
ok,

I'll merge the changes into master, and then we'll need to backport them into 1.x.

Thanks

**Comment by uriavraham** [comment]
Thanks.

**Pull request merged**
